import test from 'node:test';
import assert from 'node:assert/strict';
import { createCityRuntime, createMemoryStore, createRailLink, WORK_STATE } from '../src/city-runtime.mjs';
import { createCityService } from '../src/city-entry.mjs';

test('new city map uses DWARF.ARTIFACT as the workshop, not a postal actor', () => { const runtime = createCityRuntime({ sourceSha: 'a'.repeat(40) }); assert.deepEqual(runtime.map.components, ['METROPOLIS', 'CITY_HALL', 'WORK_SYSTEM', 'POST_OFFICE', 'DWARF_ARTIFACT', 'SHOP', 'SPECTRUMSALE', 'THE_TAILOR']); assert.equal(runtime.map.paths.includes('HALL_TO_DWARF_ARTIFACT'), true); assert.equal(runtime.map.paths.includes('HALL_TO_PIXIE_SERVICE'), false); });
test('Rail Link has exactly two Station endpoints and one trust boundary', () => { const link = createRailLink({ railId: 'RAIL-MF', endpoints: [{ stationId: 'METROPOLIS_STATION', systemId: 'METROPOLIS' }, { stationId: 'FACTORY_STATION', systemId: 'FACTORY' }], trustBoundary: 'METROPOLIS_FACTORY' }); assert.equal(link.endpoints.length, 2); assert.throws(() => createRailLink({ railId: 'bad', endpoints: [{ stationId: 'A', systemId: 'A' }], trustBoundary: 'x' }), /EXACTLY_TWO/); });
test('Work identity remains stable across intake, handoff and return', async () => { const runtime = createCityRuntime({ store: createMemoryStore(), idFactory: (() => { let n = 0; return () => `ID-${++n}`; })() }); const received = await runtime.intake({ workId: 'WORK-1', ownerSystem: 'FACTORY', requestedBy: 'GO' }); const handed = await runtime.handoff({ workId: 'WORK-1', checkpointId: received.checkpointId, stationId: 'FACTORY_STATION', railId: 'RAIL-MF', operation: 'EXECUTE' }); const returned = await runtime.returnWork({ workId: 'WORK-1', checkpointId: received.checkpointId, readback: { owner: 'FACTORY' }, evidenceRefs: ['evidence://1'], verified: true }); assert.equal(handed.workId, 'WORK-1'); assert.equal(returned.workId, 'WORK-1'); assert.equal(returned.state, WORK_STATE.RETURNED); });
test('Agent can disconnect while city and mailbox infrastructure remain available', async () => { const runtime = createCityRuntime(); runtime.registerMailbox({ mailboxId: 'MAILBOX-GO', owner: 'GO', receiver: 'GO' }); runtime.connectAgent({ agentId: 'GO', secretaryId: 'SEC-GO', mailboxId: 'MAILBOX-GO', role: 'ACTOR' }); assert.equal(runtime.disconnectAgent('GO').state, 'DISCONNECTED'); const cargo = await runtime.sendCargo({ dataId: 'DATA-1', dataKind: 'EVIDENCE', payloadRef: 'evidence://1', owner: 'FACTORY', sender: 'FACTORY', receiver: 'GO', mailbox: 'MAILBOX-GO', destination: 'GO', workId: 'WORK-1', checkpointId: 'WORK-1:CP-01' }); assert.equal(cargo.status, 'DELIVERED'); });
test('wrong checkpoint never mutates Work', async () => { const runtime = createCityRuntime(); await runtime.intake({ workId: 'WORK-2', ownerSystem: 'FACTORY' }); await assert.rejects(() => runtime.handoff({ workId: 'WORK-2', checkpointId: 'wrong', stationId: 'FACTORY_STATION', railId: 'RAIL-MF', operation: 'EXECUTE' }), /CHECKPOINT_MISMATCH/); assert.equal((await runtime.getWork('WORK-2')).state, WORK_STATE.RECEIVED); });
test('City service exposes health and Work intake', async () => { const runtime = createCityRuntime({ sourceSha: 'b'.repeat(40) }); const service = createCityService({ runtime }); assert.equal((await (await service.fetch(new Request('https://metropolis.example/health'))).json()).status, 'READY'); const intake = await service.fetch(new Request('https://metropolis.example/work/intake', { method: 'POST', body: JSON.stringify({ workId: 'WORK-3', ownerSystem: 'FACTORY' }) })); assert.equal(intake.status, 201); });
